[tool.poetry]
name = "pipedream component code gen"
version = "0.0.1"
description = "Generate Pipedream component code using AI"
authors = ["Pipedream <pipedream@pipedream.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
openai = "^0.27.8"
python-dotenv = "^1.0.0"
langchain = "0.0.331rc1"
supabase = "^1.0.3"
selenium = "^4.12.0"
markdown-to-json = "^2.1.0"
gitpython = "^3.1.40"
scikit-learn = "^1.3.2"
html2text = "^2020.1.16"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
component_code_gen = 'run:main'
