on: 
  push:
    branches:
      - master
      - lerna


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v3.2.0
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: install
        run: npm ci
      - run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: publish
        run: npx lerna --loglevel debug publish from-package --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: debug lerna
        if: ${{ failure() }}
        run: cat lerna-debug.log
