on:
  push:
    branches:
      - platform-1.x
      - platform-2.x

jobs:
  # See https://pnpm.io/continuous-integration#github-actions
  publish:
    name: pnpm publish
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: pnpm/action-setup@v4.2.0
        with:
          version: 9.14.2
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - name: pnpm install
        run: pnpm install -r --no-frozen-lockfile
      - name: Compile TypeScript
        run: pnpm run build
      # See https://pnpm.io/using-changesets
      - name: Setup npmrc for pnpm publish
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: pnpm publish (platform)
        run: pnpm publish platform --no-git-checks
